### ISSUE TITLE
Publish new version (ie. from 0.9.25 to 0.9.26)

### ISSUE THREAD

**Issue by silbinarywolf** [aurelia/template-lint#191]
As per this PR comment:
https://github.com/aurelia/template-lint/pull/189#issuecomment-455040115

Waiting on @MeirionHughes to reply back and give @AureliaEffect npm publishing rights.
cc @EisenbergEffect 

I wanted to create an explicit issue that's open so other users can be made aware of what we're waiting on.

**Comment by silbinarywolf** [comment]
@EisenbergEffect Are we able to get this published?

**Comment by EisenbergEffect** [comment]
Just got internet back after snow storm took it out for a day and a half :) I'm looking into this now. Might take a day or two since I need to look into details a bit more and see if there's anything special in the publish process. Thanks for your patience @silbinarywolf

**Comment by silbinarywolf** [comment]
Ah thats rough! We've had flooding / heavy rain down here too lately!
There's no urgency on this so don't feel the need to rush to it, I'd just like to have a lingering todo item covered off within the next month or so!

**Comment by EisenbergEffect** [comment]
Sadly, this repo doesn't build 😢I'm going to have to dig in and try to find out what's going on.  Might take a bit of time.

**Comment by EisenbergEffect** [comment]
I've pushed a new version to master that updates some dependencies. The current issue appears to be that the TypeScript compiler APIs have changed. Since I'm less familiar with the internal AST APIs, I'm not sure what the correct way is to convert from the old code to the new code. The errors are in one file: `source/rules/bindings.ts`. Does anyone here have familiarity with this who could submit a PR? Also including @fkleuver since I know he's messed with TS compiler APIs a bit as well and may be able to make a quick fix. It's only six errors, very similar in nature, that need correction. I can did further myself, but though I would put it out to the group to see if anyone already had this knowledge.

**Comment by silbinarywolf** [comment]
That's essentially the issue I hit while trying to update this. The AST APIs have all changed.

**Comment by EisenbergEffect** [comment]
I'm hoping the fix is obvious to @fkleuver :) If not or if he doesn't get around to it, then I'll plan to tackle this in a few days.

**Comment by fkleuver** [comment]
It appeared to be a fairly straight-forward fix (that is, if things actually still work). See https://github.com/aurelia/template-lint/pull/192
@silbinarywolf @EisenbergEffect 

I can't get the rests to run:
![image](https://user-images.githubusercontent.com/9655331/54087961-dc141f00-4358-11e9-9f34-44ba74801702.png)

**Comment by EisenbergEffect** [comment]
Thanks for taking time to look into this @fkleuver I was going to sit down today and figure it out...so your timing is impeccable 🤣 

@silbinarywolf Can you try this out in your app and see if it gets you going again?

**Comment by silbinarywolf** [comment]
Not sure what you mean by "get us going again"?

The current tagged version is functioning OK, it'll just be painful if somebody on my team hits the bug I fixed in my PR from a couple of months ago :) ie. unclosed HTML tags.

**Comment by EisenbergEffect** [comment]
I mainly meant, can you confirm if what's in master now works for you, now that we've updated the compiler and got it building again.

**Comment by silbinarywolf** [comment]
Yep sure. I'll set aside some time this week to do this :)

**Comment by EisenbergEffect** [comment]
Awesome. Thank you @silbinarywolf !

**Comment by silbinarywolf** [comment]
Its working fine for my use-case! However it's worth noting that we currently don't have `typeChecking` running over the project. (We've yet to fix up all the errors its throwing as we've installed the plugin ~3 years after the project was started)

**Comment by EisenbergEffect** [comment]
Excellent. Thanks!

**Comment by EisenbergEffect** [comment]
I published 0.10.0.

**Comment by silbinarywolf** [comment]
@EisenbergEffect Thanks! Perhaps tag the Git repo with that version too :)

**Comment by EisenbergEffect** [comment]
Yep, that's next :)
